monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        file_all:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%-all.log'
            level: info
            channels: [ "!event", "!doctrine", "!request" ]

        main:
            type: fingers_crossed
            action_level: error
            handler: main_router
            excluded_http_codes: [ 400, 401, 403, 404, 405, 409 ]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks

        # routing fingers_crossed handler output to multiple handlers
        main_router:
            type: group
            members: [ file_error ]

        file_error:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%-error.log'
            level: info

        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine", "!console" ]

when@prod:
    monolog:
        handlers:
            # routing fingers_crossed handler output to multiple handlers
            main_router:
                type: group
                members: [ file_error, console ]